services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: azubi-africa-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - azubui-africa-app-network
    restart: always

  mongo:
    image: mongo:8.0.1
    container_name: azubi-africa-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - azubui-africa-app-network
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: azubi-africa-frontend
    ports:
      - "80:80"
    environment:
      - VITE_APP_BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - azubui-africa-app-network
    restart: always

volumes:
  mongo-data:

networks:
  azubui-africa-app-network:
    driver: bridge
